### ISSUE TITLE
Doesn't work on StackBlitz

### ISSUE THREAD

**Issue by XhmikosR** [bcomnes/npm-run-all2#108]
Hey, @bcomnes.

I recently started switching my projects to npm-run-all2 and overall it's been a smooth switch.

That being said, I noticed that StackBlitz doesn't work with npm-run-all2. I suspect it has to do with one of the npm path changes in the recent versions.

* Using npm-run-all: https://stackblitz.com/github/twbs/examples/tree/284cb72da8429c58e3a90b7789e09f65fe7accc7/color-modes?file=index.html
* Using npm-run-all2: https://stackblitz.com/github/twbs/examples/tree/039aecfbaea8447d3d4bc946681c09e921c777a9/color-modes?file=index.html

```sh
$ npm-run-all --parallel watch server
ERROR: The "path" argument must be of type string. Received undefined
```

IIRC StackBlitz is using turbopack, but it'd be nice if npm-run-all2 could also work on StackBlitz.

**Comment by bcomnes** [comment]
Possible related to https://github.com/bcomnes/npm-run-all2/commit/61e84ea44dd5c54a6d8a4e1bc9598ed989dfee01 ?

**Comment by bcomnes** [comment]
Seems like an issue with stackbliz but open to fixes if it improves things there and doesn't make things worse here. Closing the issue until someones willing to submit a PR.
