### ISSUE TITLE
6.1.0: TypeError: minimatch is not a function

### ISSUE THREAD

**Issue by zloirock** [bcomnes/npm-run-all2#121]
6.0.6 works fine.

```
/home/runner/.npm/_npx/755986f37193a6d8/node_modules/run/run.js:127
        if (minimatch(file, pattern)) {
            ^

TypeError: minimatch is not a function
```

https://github.com/zloirock/core-js/actions/runs/6409506993/job/17401122777

The only change in those tasks is this `npm-run-all2` bump, https://github.com/zloirock/core-js/commit/2bd2697232c05b630e47fb0ca27026502db235fe

On local macOS 14.0 with Node 20.8.0 and `npm` 10.1.0  it works fine.

**Comment by zloirock** [comment]
After downgrading on the local machine to Node 16.13.2 with `npm` 8.1.2, on steps from CI, I have:

![image](https://github.com/bcomnes/npm-run-all2/assets/2213682/c2b0ca93-37e1-49f2-9560-93d333a66eca)

It looks like a possible regression of https://github.com/bcomnes/npm-run-all2/issues/93

**Comment by bcomnes** [comment]
Sorry about that. Run the older version for now and I'll look into the issue. Thanks for raising it.

**Comment by bcomnes** [comment]
Looks like a minor logic error.  @kinland I landed a fix in https://github.com/bcomnes/npm-run-all2/commit/cfbd974a5990e8d549ae8bf7bfb632424ff4990b want to have a second look? 

Need to get some test coverage in on the npx use case. 

Can you try out https://github.com/bcomnes/npm-run-all2/releases/tag/v6.1.1 ?

**Comment by zloirock** [comment]
It seems it's fixed, thanks -)
