### ISSUE TITLE
Why is there inconsistency in the behavior of npm, yarn, and pnpm when using the @ parameter placeholder?

### ISSUE THREAD

**Issue by mishengqiang** [bcomnes/npm-run-all2#124]
In the [create-vue](https://github.com/vuejs/create-vue) project, the ```@``` placeholder is used, but there is inconsistency in behavior between npm, yarn, and pnpm. See details at https://github.com/vuejs/create-vue/pull/394#issuecomment-1833596570.

**Comment by bcomnes** [comment]
Closing due to lack of specifics here. Happy to reopen when we can clarify these issues. I don't have time at the moment to investigate.
