### ISSUE TITLE
`run-p 'build:*'` is not supported on Windows with `yarn` v4

### ISSUE THREAD

**Issue by JounQin** [bcomnes/npm-run-all2#125]
https://github.com/un-ts/mono-lib-boilerplate/actions/runs/7129094026/job/19412404414?pr=47#step:6:12

```log
$ run-p 'build:*'
ERROR: Task not found: "'build:*'"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by bcomnes** [comment]
Only suggestion I could make would be to try to maybe remove the quotes around the globbed task `run-p build:*`, but there could very well be an incompatibility at play here. This tools is not well tested on windows power shell or with yarn > v2. 

Open to PRs if anyone is interested in digging into this, but unfortunately I don't have the bandwidth or interest at the moment to personally spend time on this. 

Closing to indicate that but happy to reopen if someone is interested.

**Comment by JounQin** [comment]
OK, I'm interested to raise a fix, please reopen and assign to me.

**Comment by bcomnes** [comment]
Hey @JounQin any progress?

**Comment by JounQin** [comment]
@bcomnes Not right now, I'm focusing on other things these days, but this is still on my schedule.

**Comment by bcomnes** [comment]
Closing this issue as not planned for now since it doesn't seem like a widespread issue.  If you end up looking into it, I'll consider any PRs you come up with.
