### ISSUE TITLE
Add note about pnpm support in README.md

### ISSUE THREAD

**Issue by shion1305** [bcomnes/npm-run-all2#135]
Hi there!
I was wondering whether this tool supports pnpm and found #117 that says it does.
However, I do not see any notes about pnpm support in README.md.
Could you update the document and include a note on pnpm support?
Thank you for your consideration!

**Comment by voxpelli** [comment]
PR welcome :)

**Comment by shion1305** [comment]
@voxpelli Thanks for your comment. I submitted a PR!
