### ISSUE TITLE
--print-label strips colors from log ouput

### ISSUE THREAD

**Issue by bcomnes** [bcomnes/npm-run-all2#137]
When using the `--print-label` option, colors are stripped from the log output. It would be preferable if that wasn't the case.

**Comment by travi** [comment]
a potential related approach to possibly consider: https://github.com/mysticatea/npm-run-all/issues/131

**Comment by bcomnes** [comment]
Oh good technique. Will add it to the docs. I noticed that there is already a known issues section.

**Comment by voxpelli** [comment]
If it's eg chalk that deactivate the color then we should maybe check if we could upstream it to not just check TTY but also that env variable?

**Comment by bcomnes** [comment]
The force color env var works pretty well.  Been playing with that.

**Comment by bcomnes** [comment]
Using env vars and whatnot, I think thats probably the best solution with this flag for now.
