### ISSUE TITLE
[BUG] nodemon v2.0.6 not working with npm-run-all --parallel in nodejs 20

### ISSUE THREAD

**Issue by danny007in** [bcomnes/npm-run-all2#139]
Follow up link please https://github.com/mysticatea/npm-run-all/issues/194

**Comment by bcomnes** [comment]
Just tested it locally and it works fine. Make a new issue with a minimal reproducible gist or repo.

**Comment by danny007in** [comment]
https://github.com/mysticatea/npm-run-all/issues/25

Please Check This

**Comment by bcomnes** [comment]
Upstream seems abandoned, and things have diverted quite a bit over the last few years. If you have a minimal reproducible gist or repo that demonstrates a real bug, I will consider it. Thank you!
