### ISSUE TITLE
Relicense as blue oak

### ISSUE THREAD

**Issue by bcomnes** [bcomnes/npm-run-all2#140]
I maintain npm-run-all2 for my own personal ends, as well as the benefit of anyone else who hoped aboard. What do people think about relicensing under blue oak? From my end, I have no qualms, since I have no personal commercial interests in this project.  Is that even allowed?

- https://blueoakcouncil.org/license/1.0.0

**Comment by BrycensRanch** [comment]
https://opensource.org/license/blue-oak-model-license states it is a redundant license with more popular alternatives available. I had to google search it as I didn't even know what it was. MIT allows commercial usage https://opensource.org/license/mit

**Comment by bcomnes** [comment]
Edited in a URL reference. There is some drama behind the scene iirc about adding a new license, however the improvements around implicit CLAs that sound like nice improvements.

**Comment by voxpelli** [comment]
I'm torn on relicensing, especially as that has to be done by the book

I would prefer sticking with what we already have

**Comment by bcomnes** [comment]
Ok lets do that then.
