### ISSUE TITLE
Update cross-spawn dependency to ^7.0.6

### ISSUE THREAD

**Issue by haakonrp** [bcomnes/npm-run-all2#165]
Got this security warning in my repo:

Versions of the package cross-spawn before 7.0.5 are vulnerable to Regular Expression Denial of Service (ReDoS) due to improper input sanitization. An attacker can increase the CPU usage and crash the program by crafting a very large and well crafted string.
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/73fcbfaf-9860-4570-8242-976302db36ee">

**Comment by bcomnes** [comment]
We can raise the range floor on this, no problem. In the meantime you can always regenerate your lockfile, or perform targeted updates to it.

**Comment by bcomnes** [comment]
https://github.com/bcomnes/npm-run-all2/commit/45a9e191b75e0b76433409808b6219d1f4dffe83

**Comment by bcomnes** [comment]
This is being released in 7.0.2, released shortly https://github.com/bcomnes/npm-run-all2/actions/runs/12357565440/job/34486119059
