### ISSUE TITLE
Extend engine definition to `^14.18.0 || >=16.0.0`

### ISSUE THREAD

**Issue by voxpelli** [bcomnes/npm-run-all2#86]
See eg: https://twitter.com/MylesBorins/status/1521619664723402753

Else eg. my `installed-check` will complain that this module won't work with Node 14, and I run that tool in my tests: https://github.com/voxpelli/pony-cause/blob/90a012f694aee8bbeede1e4fc0b7a29d4ff2b227/package.json#L31

**Comment by bcomnes** [comment]
Done. https://github.com/bcomnes/npm-run-all2/runs/6883945856?check_suite_focus=true is running the release. Will be done soon.
