### ISSUE TITLE
Make it work with `npx`

### ISSUE THREAD

**Issue by zloirock** [bcomnes/npm-run-all2#93]
Original issue: https://github.com/mysticatea/npm-run-all/issues/209

**Comment by bcomnes** [comment]
Probably should fix this. Anyone attempt patches upstream I can pull in?

**Comment by zloirock** [comment]
https://github.com/mysticatea/npm-run-all/pull/245

**Comment by bcomnes** [comment]
Cool ty. I'll look at getting that merged and tested.

**Comment by MarmadileManteater** [comment]
I could formally move my PR over to this repo if y'all would appreciate that. I hadn't realized someone else was trying to maintain this repo. I have just been using my fork because this bug bothers me so much.

**Comment by bcomnes** [comment]
@MarmadileManteater That would be great and I appreciate it!

**Comment by bcomnes** [comment]
https://github.com/bcomnes/npm-run-all2/releases/tag/v6.0.3 

Reopen if there are issue

**Comment by zloirock** [comment]
It seems it's still not fixed

![image](https://user-images.githubusercontent.com/2213682/200904550-b9a71607-c448-4019-9212-c0bb6ce93a43.png)

@MarmadileManteater

**Comment by MarmadileManteater** [comment]
![image](https://user-images.githubusercontent.com/106682128/200906343-d30f5b8a-9c66-4c8a-879e-6d6477c0e91b.png)
I've never tested this code on a mac, so I wonder 🤔 if that has something to do with it.

**Comment by bcomnes** [comment]
@MarmadileManteater https://github.com/bcomnes/npm-run-all2/pull/96

**Comment by MarmadileManteater** [comment]
I pulled `process.env.npm_config_user_agent` from the npm package [`is-npm`](https://github.com/sindresorhus/is-npm/blob/main/index.js), and as far as I can tell that exists outside of Windows, but  `NPM_CLI_JS` looks like it might be defined only in Windows because it isn't showing up on my linux machine, and I never explicitly defined it myself. This seems to be an oversight on my part. 

This could be addressed by looking for `npm_cli.js` in the same directory that `npx_cli.js` is in since `npm_execpath` seems to exist on all systems.

**Comment by bcomnes** [comment]
> This could be addressed by looking for npm_cli.js in the same directory that npx_cli.js is in since npm_execpath seems to exist on all systems.

Great minds think alike!

**Comment by zloirock** [comment]
Yep, at debugging I see:
```
options.npmPath: null
process.env.NPM_CLI_JS: undefined
process.env.npm_execpath: /usr/local/lib/node_modules/npm/bin/npx-cli.js
npmPath: /usr/local/lib/node_modules/npm/bin/npx-cli.js
npmPathIsJs: true
execPath: /usr/local/bin/node
```
so #96 looks like a proper fix.

**Comment by bcomnes** [comment]
Ok everyone give https://github.com/bcomnes/npm-run-all2/releases/tag/v6.0.4 a whirl.

**Comment by zloirock** [comment]
It works for me, thanks 👍
